name: 'Azure SQL DB Deployment'

trigger:
- none
variables:
  - name:  SqlProjects
    value: metadata.control, metadata.ingest, metadata.transform

stages:
  - stage: BuildAndPublish
    displayName: Build And Publish Sql Projects
    jobs:
      - job: InstallPackets
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
          - task: NuGetToolInstaller@1
            inputs:
              versionSpec: 
          - task: NuGetCommand@2
            inputs:
              restoreSolution: false
              feedsToUse: 'select'
              includeNuGetOrg: true
              nuGetConfigPath: 'NuGet.config'
              nuGetFeedType: 'internal'
      - job: Build
        dependsOn: InstallPackets
        pool:
          vmImage: 'windows-latest'
        steps:
          - ${{ each SqlProject in split(variables.SqlProjects, ', ') }}:
            - task: VSBuild@1
              displayName: Build ${{ SqlProject }}
              inputs:
                solution:  '$(System.DefaultWorkingDirectory)/src/${{ SqlProject }}//${{ SqlProject }}.sqlproj'
                msbuildArgs: '/p:Configuration=Release'
                platform: 'Any CPU'
                configuration: 'Release'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/src'
              Contents: '**/bin/**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'        
          - publish: '$(Build.ArtifactStagingDirectory)'
            artifact: 'SqlArtifacts'
