name: 'Data Infrastructure Deployment'

parameters:
- name: dev
  displayName: 'Deploy to Development Environment'
  type: object
  default: 
    enabled: true
    subscriptionName: 'Dev Connection'

- name: test
  displayName: 'Deploy to Test Environment'
  type: object
  default: 
    enabled: false
    subscriptionName: 'Dev Connection'

- name: prod
  displayName: 'Deploy to Production Environment'
  type: object
  default: 
    enabled: false
    subscriptionName: 'Dev Connection'

# trigger:
# - main

stages:
  - ${{ each pair in parameters }}:
      - ${{ if eq(pair.value.enabled, true) }}:
          - stage: BicepDeployment_${{ pair.key }}
            displayName: 'Bicep Deployment Stage to ${{ upper(pair.key) }} Environment'
            variables:
              azureSubscription: ${{ pair.value.subscriptionName }}
            jobs:
            - job: BicepPreview_${{ pair.key }}
              displayName: 'Bicep Preview to ${{ upper(pair.key) }} Environment'
              steps:
                - task: AzureCLI@2
                  displayName: 'Azure CLI for Bicep Preview'
                  inputs:
                    azureSubscription: ${{ variables.azureSubscription }}
                    addSpnToEnvironment: true
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      echo "Starting Bicep Preview (What-If Operation) in environment ${{ pair.key }}"
                      az deployment sub what-if --name Deployment_${{ pair.key }}_$(date +'%Y%m%d%H%M%S') --template-file ./infrastructure/main.bicep --parameters ./infrastructure/configuration/${{ pair.key }}/main.bicepparam --location uksouth

            # - job: ManualValidation_${{ pair.key }}
            #   displayName: 'Manual Validation for ${{ upper(pair.key) }} Environment'
            #   pool: server
            #   dependsOn: BicepPreview_${{ pair.key }}
            #   timeoutInMinutes: 1440
            #   steps:
            #     - task: ManualValidation@0
            #       inputs:
            #         instructions: 'Please validate the Bicep preview before proceeding to deployment.'

            - job: BicepDeploy_${{ pair.key }}
              displayName: 'Bicep Deployment to ${{ upper(pair.key) }} Environment'
              dependsOn: BicepPreview_${{ pair.key }}
              dependsOn: ManualValidation_${{ pair.key }}
              condition: >
                and(succeeded(),
                  or(
                    ne('${{ pair.key }}', 'prod'), 
                    and(eq('${{ pair.key }}', 'prod'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
                  )
                )
              steps:
                - task: AzureCLI@2
                  displayName: 'Azure CLI for Bicep Deployment'
                  inputs:
                    azureSubscription: ${{ variables.azureSubscription }}
                    addSpnToEnvironment: true
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      echo "Starting Bicep Deployment in environment ${{ pair.key }}"
                      az deployment sub create --name Deployment_${{ pair.key }}_$(date +'%y-%m-%d-%H%M') --template-file ./infrastructure/main.bicep --parameters ./infrastructure/configuration/${{ pair.key }}/main.bicepparam --location uksouth
