name: Bug Found
about: Tell me about the bug you've found in the CF.Cumulus
title: ''
labels: bug
assignees: ["CloudFormations"]
body:
  type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature you are suggesting.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: A button in the screen X that allows to do Y
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: It should be implemented because
      placeholder: It will allow to do Y that is needed for Z
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: |
        Add any other context or screenshots about the feature request here.
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! Let's see together if it can be implemented.
   
   
   
   
   
   
   
   
   
   
   - type: checkboxes
       id: terms
       attributes:
         label: Which resource within the processing framework does this affect?
         options:
         - label: Data Factory/Synapse
         - label: SQL Database
         - label: Functions
         - label: All of them
         - label: Other        
   - type: textarea
       id: description
       attributes:
         label: Describe your issue
         placeholder: When I click here this happens
       validations:
         required: true
           - type: textarea
       id: steps
       attributes:
         label: Steps to reproduce
         placeholder: |
           1. Go to page X
           2. Click here
           3. Click there
       validations:
         required: true
   - type: textarea
       id: expected
       attributes:
         label: What was the expected result?
         placeholder: I expected this to happen
   - type: textarea
     id: screenshots
     attributes:
         label: Put here any screenshots or videos (optional)
   - type: markdown
     attributes:
       value: |
           Thanks for reporting this issue! We will get back to you as soon as possible.
   
