name: Bug Found
about: Tell me about the bug you've found in the CF.Cumulus
title: ''
labels: bug
assignees: ["CloudFormations"]
body:
  - type: markdown
    attributes:
      value:
        Please fill out the sections below to help everyone identify and fix the bug
   - type: checkboxes
       id: terms
       attributes:
         label: Which resource within the processing framework does this affect?
         options:
         - label: Data Factory/Synapse
         - label: SQL Database
         - label: Functions
         - label: All of them
         - label: Other        
   - type: textarea
       id: description
       attributes:
         label: Describe your issue
         placeholder: When I click here this happens
       validations:
         required: true
           - type: textarea
       id: steps
       attributes:
         label: Steps to reproduce
         placeholder: |
           1. Go to page X
           2. Click here
           3. Click there
       validations:
         required: true
   - type: textarea
       id: expected
       attributes:
         label: What was the expected result?
         placeholder: I expected this to happen
   - type: textarea
     id: screenshots
     attributes:
         label: Put here any screenshots or videos (optional)
   - type: markdown
     attributes:
       value: |
           Thanks for reporting this issue! We will get back to you as soon as possible.
   
