  # Job to build and publish the dacpac
name: CF.Cumulus-Sql-Server-Control-CICD
on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main

jobs: 
  build_control:
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2.4.2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Build Database project
      run: |
        msbuild.exe src/metadata.control/metadata.control.sqlproj /p:Configuration=Release
    - uses: actions/upload-artifact@v4
      with: 
        name: controlartifact
        path: ${{ github.workspace }}/src/metadata.control/bin/Release/

# Deploy dacpac job
  deploy_dev:
    # Set the dependency for the build job
    needs: build_control
    runs-on: windows-latest
    environment: dev

    steps:
      - name: download artifact containing dacpac
        uses: actions/download-artifact@v4
        with:
          name: controlartifact  # Match the uploaded artifact name
          path: ${{ github.workspace }}/src/metadata.control/bin/Release/

      - name: Verify Artifact File
        run: ls -R ${{ github.workspace }}/src/metadata.control/bin/Release/

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.3
        with:
          connection-string: "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
          path: ${{ github.workspace }}/src/metadata.control/bin/Release/metadata.control.dacpac
          action: 'publish'
          arguments: '/v:TenantID="${{ secrets.AZURE_TENANT_ID }}"  /v:Environment="Dev"  /v:ADFName="${{ secrets.ADFNAME }}"  /v:RGName="${{ secrets.RGNAME }}" /v:SubscriptionID="${{ secrets.AZURE_SUBSCRIPTION_ID }}" '

# Deploy dacpac job
  deploy_test:
    # Set the dependency for the build job
    needs: deploy_dev
    runs-on: windows-latest
    environment: test

    steps:
      - name: download artifact containing dacpac
        uses: actions/download-artifact@v4
        with:
          name: controlartifact  # Match the uploaded artifact name
          path: ${{ github.workspace }}/src/metadata.control/bin/Release/

      - name: Verify Artifact File
        run: ls -R ${{ github.workspace }}/src/metadata.control/bin/Release/

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.3
        with:
          connection-string: "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
          path: ${{ github.workspace }}/src/metadata.control/bin/Release/metadata.control.dacpac
          action: 'publish'
          arguments: '/v:TenantID="${{ secrets.AZURE_TENANT_ID }}"  /v:Environment="Test"  /v:ADFName="${{ secrets.ADFNAME }}"  /v:RGName="${{ secrets.RGNAME }}" /v:SubscriptionID="${{ secrets.AZURE_SUBSCRIPTION_ID }}" '


# Deploy dacpac job
  deploy_prod:
    # Set the dependency for the build job
    needs: deploy_test
    runs-on: windows-latest
    environment: prod

    steps:
      - name: download artifact containing dacpac
        uses: actions/download-artifact@v4
        with:
          name: controlartifact  # Match the uploaded artifact name
          path: ${{ github.workspace }}/src/metadata.control/bin/Release/

      - name: Verify Artifact File
        run: ls -R ${{ github.workspace }}/src/metadata.control/bin/Release/

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.3
        with:
          connection-string: "${{ secrets.AZURE_SQL_CONNECTION_STRING }}"
          path: ${{ github.workspace }}/src/metadata.control/bin/Release/metadata.control.dacpac
          action: 'publish'
          arguments: '/v:TenantID="${{ secrets.AZURE_TENANT_ID }}"  /v:Environment="Prod"  /v:ADFName="${{ secrets.ADFNAME }}"  /v:RGName="${{ secrets.RGNAME }}" /v:SubscriptionID="${{ secrets.AZURE_SUBSCRIPTION_ID }}" '
