name: Run Python Unit Testing on Cluster
  
on: 
  pull_request:
  workflow_dispatch:

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  
jobs:  
  run-python-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:        
      - name: Checkout repo
        uses: actions/checkout@v4 
      - name: Unit tests for PySpark Notebooks on Databricks
        uses: databricks/run-notebook@main
        with:
          databricks-token: ${{ secrets.DATABRICKS_TOKEN }}

          local-notebook-path: src/azure.databricks/python/tests/pytest_databricks.py

          existing-cluster-id: ${{ secrets.DATABRICKS_CLUSTER_ID}}

          git-commit: "${{ github.event.pull_request.head.sha }}"

          # Grant all users view permission on the notebook's results, so that they can
          # see the result of the notebook, if they have related access permissions.
          access-control-list-json: >
            [
              {
                "group_name": "users",
                "permission_level": "CAN_VIEW"
              }
            ]
          run-name: "EDA transforms helper module unit tests"