# Job to build and publish the dacpac
name: CF.Cumulus-Sql-Server-Master-CICD
on:
  workflow_dispatch:

jobs:
# Execute core yml cicd
  exec_core:
    # Set the dependency for the build job
    uses: ${{ github.workspace }}/.github/workflows/sql-server-core-cicd.yml

# Execute core yml cicd
  exec_data:
    # Set the dependency for the build job
    needs: exec_core
    uses: ${{ github.workspace }}/.github/workflows/sql-server-data-cicd.yml
